# Generated by Django 4.0 on 2022-03-02 14:43

import base_app.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('text', models.TextField(max_length=8192, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_lectures', to='auth.user', verbose_name='Author')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='course_app.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LectureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=base_app.utils.get_unique_filename, verbose_name='File')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_lecture_files', to='auth.user', verbose_name='Author')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='lecture_app.lecture', verbose_name='Lecture')),
            ],
            options={
                'verbose_name': 'Lecture file',
                'verbose_name_plural': 'Lecture files',
            },
        ),
    ]
