version: "3.7"

services:
  redis:
    image: redis
    restart: always
    volumes:
      - ./courses/data/redis:/data
    env_file: ./.env

  worker_default:
    restart: always
    build:
      context: ./courses
    volumes:
      - ./courses:/app
    entrypoint: []
    command: ["./wait-for-it.sh", "db:5432", "--", "celery", "--workdir=./src", "-A", "courses", "worker", "-Q", "default"]
    env_file: ./.env
    depends_on:
      - redis
      - beat
      - db

  worker_email:
    restart: always
    build:
      context: ./courses
    volumes:
      - ./courses:/app
    entrypoint: []
    command: ["./wait-for-it.sh", "db:5432", "--", "celery", "--workdir=./src", "-A", "courses", "worker", "-c", "1", "-Q", "email"]
    env_file: ./.env
    depends_on:
      - redis
      - beat
      - db

  beat:
    restart: always
    build:
      context: ./courses
    volumes:
      - ./courses:/app
    entrypoint: []
    command: ["./wait-for-it.sh", "db:5432", "--", "celery", "--workdir=./src", "-A", "courses", "beat", "-l", "INFO", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
    env_file: ./.env
    depends_on:
      - redis
      - db

  courses:
    restart: always
    build:
      context: ./courses
    ports:
      - "8000:8000"
    volumes:
      - ./courses:/app
    entrypoint: []
    command: ["./wait-for-it.sh", "db:5432", "--", "./courses_run.sh"]
    env_file: ./.env
    depends_on:
      - redis
      - beat
      - worker_default
      - worker_email
      - db

  flower:
    restart: always
    build:
      context: ./courses
    ports:
      - "5555:5555"
    entrypoint: []
    command: ["celery", "--workdir=./src", "-A", "courses", "flower"]
    env_file: ./.env
    depends_on:
      - beat
      - redis
      - worker_default
      - worker_email

  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./courses/data/postgres:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
