version: "2.2"

services:
  redis:
    image: redis
    restart: always
    env_file: ./.env

  worker:
    restart: always
    build:
      context: ./courses
    command: ["celery", "--workdir=./src", "-A", "courses", "worker"]
    env_file: ./.env
    depends_on:
      redis:
        condition: service_started
      beat:
        condition: service_started
      db:
        condition: service_healthy

  beat:
    restart: always
    build:
      context: ./courses
    command: ["celery", "--workdir=./src", "-A", "courses", "beat", "-l", "INFO", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
    env_file: ./.env
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy

  courses:
    restart: always
    build:
      context: ./courses
    ports:
      - "8000:8000"
    command: ["./courses_run.bash"]
    env_file: ./.env
    depends_on:
      redis:
        condition: service_started
      beat:
        condition: service_started
      worker:
        condition: service_started
      db:
        condition: service_healthy

  flower:
    restart: always
    build:
      context: ./courses
    ports:
      - "5555:5555"
    command: ["celery", "--workdir=./src", "-A", "courses", "flower"]
    env_file: ./.env
    depends_on:
      beat:
        condition: service_started
      redis:
        condition: service_started
      worker:
        condition: service_started

  db:
    restart: always
    image: postgres
    ports:
      - '5432'
    volumes:
      - postgresqldbvolume:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresqldbvolume:
    driver: local
