version: "2.2"

services:
  redis:
    image: redis
    restart: always
    volumes:
      - redisvolume:/data
    env_file: ./.env

  worker_default:
    restart: always
    build:
      context: ./courses
    volumes:
      - ./courses/src:/app/src
    entrypoint: []
    command: ["celery", "--workdir=./src", "-A", "courses", "worker", "-Q", "default"]
    env_file: ./.env
    depends_on:
      redis:
        condition: service_started
      beat:
        condition: service_started
      db:
        condition: service_healthy

  worker_email:
    restart: always
    build:
      context: ./courses
    volumes:
      - ./courses/src:/app/src
    entrypoint: []
    command: ["celery", "--workdir=./src", "-A", "courses", "worker", "-c", "1", "-Q", "email"]
    env_file: ./.env
    depends_on:
      redis:
        condition: service_started
      beat:
        condition: service_started
      db:
        condition: service_healthy

  beat:
    restart: always
    build:
      context: ./courses
    volumes:
      - ./courses/src:/app/src
    entrypoint: []
    command: ["celery", "--workdir=./src", "-A", "courses", "beat", "-l", "INFO", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
    env_file: ./.env
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy

  courses:
    restart: always
    build:
      context: ./courses
    ports:
      - "8000:8000"
    volumes:
      - ./courses/src:/app/src
    entrypoint: []
    command: ["./courses_run.bash"]
    env_file: ./.env
    depends_on:
      redis:
        condition: service_started
      beat:
        condition: service_started
      worker_default:
        condition: service_started
      worker_email:
        condition: service_started
      db:
        condition: service_healthy

  flower:
    restart: always
    build:
      context: ./courses
    ports:
      - "5555:5555"
    entrypoint: []
    command: ["celery", "--workdir=./src", "-A", "courses", "flower"]
    env_file: ./.env
    depends_on:
      beat:
        condition: service_started
      redis:
        condition: service_started
      worker_default:
        condition: service_started
      worker_email:
        condition: service_started

  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresqldbvolume:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgresqldbvolume:
    driver: local
  redisvolume:
    driver: local
