version: "2.2"

services:
  redis:
    image: redis
    restart: always
    env_file: ./.env

  worker:
    restart: always
    build:
      context: ./courses
    command: [ "celery", "--workdir=./src", "-A", "courses", "worker" ]
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy

  courses:
    restart: always
    build:
      context: ./courses
    ports:
      - "8000:8000"
    command: ["./courses_run.bash"]
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy

  db:
    restart: always
    image: postgres
    ports:
      - '5432'
    volumes:
      - ./courses/data:/var/lib/postgresql/data
    env_file: ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
