# Generated by Django 4.0 on 2022-03-02 14:43

import course_app.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('starts_at', models.DateField(validators=[course_app.validators.validate_date], verbose_name='Start date')),
                ('ends_at', models.DateField(validators=[course_app.validators.validate_date], verbose_name='End date')),
                ('status', models.TextField(choices=[('OP', 'Open'), ('CL', 'Closed')], default='OP')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_courses', to='auth.user', verbose_name='Author')),
                ('students', models.ManyToManyField(blank=True, related_name='attending_courses', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(blank=True, related_name='teaching_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['starts_at'],
            },
        ),
    ]
