# Generated by Django 3.2.12 on 2022-03-22 13:45

from datetime import date

from django.db import migrations


def change_course_statuses(apps, schema_editor):
    Course = apps.get_model('course_app', 'Course')
    curr_date = date.today()
    for course in Course.objects.filter(ends_at__lt=curr_date, status='OP'):
        course.status = 'CL'
        course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(change_course_statuses),
    ]
