# Generated by Django 4.0 on 2022-03-02 14:43

import base_app.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lecture_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=8192, verbose_name='Text')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_tasks', to='auth.user', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('text', models.TextField(max_length=8192, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_task_statements', to='auth.user', verbose_name='Author')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statements', to='lecture_app.lecture', verbose_name='Lecture')),
            ],
            options={
                'verbose_name': 'Task statement',
                'verbose_name_plural': 'Task statements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=base_app.utils.get_unique_filename, verbose_name='File')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_task_statement_files', to='auth.user', verbose_name='Author')),
                ('task_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='task_app.taskstatement', verbose_name='Task statement')),
            ],
            options={
                'verbose_name': 'Task statement file',
                'verbose_name_plural': 'Task statement files',
            },
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=base_app.utils.get_unique_filename, verbose_name='File')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_task_files', to='auth.user', verbose_name='Author')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='task_app.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Task file',
                'verbose_name_plural': 'Task files',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_app.taskstatement', verbose_name='Task statement'),
        ),
    ]
