# Generated by Django 4.0 on 2022-03-02 14:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_value', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Mark')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_marks', to='auth.user', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Mark',
                'verbose_name_plural': 'Marks',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='auth.user', verbose_name='Author')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mark_app.mark', verbose_name='Mark')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mark_app.message', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
