# Generated by Django 4.0 on 2022-03-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mark_app', '0001_initial'),
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='task_app.task', verbose_name='Task'),
        ),
    ]
