# Generated by Django 3.2.12 on 2022-04-11 15:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='stripe_id',
            field=models.CharField(editable=False, max_length=254, unique=True, verbose_name='Stripe customer ID'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_id', models.CharField(editable=False, max_length=254, unique=True, verbose_name='Payment method ID')),
                ('name', models.CharField(max_length=254, verbose_name='Billing name')),
                ('brand', models.CharField(max_length=254, verbose_name='Brand')),
                ('country', models.CharField(max_length=32, verbose_name='Country')),
                ('exp_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Expiration month')),
                ('exp_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2022)], verbose_name='Expiration year')),
                ('fingerprint', models.CharField(max_length=254, verbose_name='Fingerprint')),
                ('funding', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('prepaid', 'Prepaid'), ('unknown', 'Unknown')], default='unknown', max_length=32, verbose_name='Funding type')),
                ('last4', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Last 4 digits')),
                ('created', models.DateTimeField(verbose_name='Created at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cards', to='payments_app.customer', verbose_name='Customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
