# Generated by Django 3.2.12 on 2022-04-13 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments_app', '0002_auto_20220411_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_id', models.CharField(editable=False, max_length=254, unique=True, verbose_name='Payment method ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('requires_payment_method', 'Requires payment method'), ('requires_confirmation', 'Requires confirmation'), ('requires_action', 'Requires action'), ('processing', 'Processing'), ('requires_capture', 'Requires capture'), ('canceled', 'Canceled'), ('succeeded', 'Succeeded')], max_length=32, verbose_name='Status')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments_app.customer', verbose_name='Customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
