# Generated by Django 3.2.12 on 2022-04-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_course_price'),
        ('payments_app', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='course_app.course', verbose_name='Course'),
        ),
    ]
