# Generated by Django 3.2.12 on 2022-04-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0004_payment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pm_id',
            field=models.CharField(editable=False, max_length=254, verbose_name='Payment method ID'),
        ),
    ]
