# Generated by Django 3.2.12 on 2022-04-13 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0005_alter_payment_pm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
