# Generated by Django 3.2.12 on 2022-04-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0006_payment_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
