# Generated by Django 3.2.12 on 2022-04-13 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0007_alter_payment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='pm_id',
            new_name='payment_method_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=254, unique=True, verbose_name='Payment intent ID'),
            preserve_default=False,
        ),
    ]
