# Generated by Django 3.2.12 on 2022-04-13 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_course_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments_app', '0008_auto_20220413_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='course',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='PaymentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='course_app.course', verbose_name='Course')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_courses', to='payments_app.payment', verbose_name='Payment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_courses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
