# Generated by Django 3.2.12 on 2022-04-14 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0009_auto_20220413_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcourse',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_course', to='payments_app.payment', verbose_name='Payment'),
        ),
    ]
